import type { MissionDef } from "./missionGamification.ts";

const T = {
  launch: { id: "launch_prod", label: "Launch & production" },
  gcc: { id: "gcc", label: "Growth Command Center" },
  dist: { id: "distribution", label: "Distribution & audience" },
  part: { id: "partnerships", label: "Partnerships & revenue" },
  comp: { id: "compliance", label: "Compliance & trust" },
  scale: { id: "global_scale", label: "Global scale milestones" },
} as const;

let order = 0;
function mission(
  key: string,
  track: { id: string; label: string },
  title: string,
  description: string,
  xp: number,
  tier: MissionDef["tier"],
  docPath?: string,
): MissionDef {
  order += 1;
  return {
    key,
    trackId: track.id,
    trackLabel: track.label,
    title,
    description,
    xp,
    tier,
    docPath,
    sortOrder: order,
  };
}

/** Full Mission HQ checklist — keep in sync with `supabase/functions/server/mission_catalog.ts`. */
export const ADMIN_MISSIONS: MissionDef[] = [
  mission(
    "prod_verify_green",
    T.launch,
    "Green verify gate",
    "Run `pnpm run verify` (typecheck, lint, test, build) after meaningful changes.",
    25,
    "standard",
  ),
  mission(
    "prod_verify_full",
    T.launch,
    "Full verify gate",
    "Run `pnpm run verify:full` including app E2E and admin Mission/E2E when touching admin or growth.",
    50,
    "major",
  ),
  mission(
    "prod_growth_check",
    T.launch,
    "Growth safety check",
    "Run `pnpm run growth:check` before enabling outbound automation.",
    25,
    "standard",
  ),
  mission(
    "prod_deploy_edge",
    T.launch,
    "Deploy Edge Function",
    "Ship latest `server` edge bundle to Supabase so public routes (`/growth/lead`, health) match repo.",
    50,
    "major",
  ),
  mission(
    "prod_migration_current",
    T.launch,
    "Migrations applied",
    "Confirm `00016_growth_command_center` (and newer) applied on production DB.",
    50,
    "major",
  ),
  mission(
    "prod_railway_configs",
    T.launch,
    "Railway configs reviewed",
    "Dockerfiles + `railway.json` for app, admin, marketing-site match `docs/RAILWAY_HOSTING.md`.",
    25,
    "standard",
    "docs/RAILWAY_HOSTING.md",
  ),
  mission(
    "prod_secrets_rotation",
    T.launch,
    "Secrets hygiene",
    "Rotate or confirm Supabase, Resend, AI, and automation keys; nothing leaked in client bundles.",
    50,
    "major",
    "docs/PRODUCTION_ACCESS.md",
  ),
  mission(
    "prod_monitoring_live",
    T.launch,
    "Monitoring ready",
    "Sentry/PostHog (if used) receive events in staging smoke; feature-flag kill switch documented.",
    25,
    "standard",
  ),
  mission(
    "prod_backup_restore_drill",
    T.launch,
    "Backup drill",
    "Run a restore or export drill for family backup flows documented.",
    25,
    "standard",
  ),
  mission(
    "prod_store_listings_draft",
    T.launch,
    "Store listings drafted",
    "App Store + Play listing copy, screenshots, andkeywords in review—not placeholder.",
    50,
    "major",
  ),
  mission(
    "prod_status_page",
    T.launch,
    "Status / comms plan",
    "Define how you announce incidents to parents (email, in-app, social)—even a one-pager.",
    25,
    "standard",
  ),

  mission(
    "gcc_daily_okr",
    T.gcc,
    "Log today’s OKR",
    "Create or update today’s daily OKR in Growth Command Center with owner + evidence habit.",
    25,
    "standard",
  ),
  mission(
    "gcc_score_okr",
    T.gcc,
    "Score yesterday’s OKR",
    "Score prior day OKR (honest base/stretch/over) and note one lesson.",
    25,
    "standard",
  ),
  mission(
    "gcc_revenue_checkpoint",
    T.gcc,
    "Log revenue checkpoint",
    "Add at least one cash/signed/pipeline checkpoint with evidence link.",
    25,
    "standard",
  ),
  mission(
    "gcc_readiness_review",
    T.gcc,
    "Readiness sweep",
    "Update subsystem readiness scores after a real P0/P1 triage pass.",
    50,
    "major",
  ),
  mission(
    "gcc_kill_switch_drill",
    T.gcc,
    "Kill-switch drill",
    "Toggle a kill switch in staging (then restore) so the team knows the muscle memory.",
    50,
    "major",
  ),
  mission(
    "gcc_approval_queue_zero",
    T.gcc,
    "Approval queue triage",
    "Drive pending approvals to decided or snoozed with owner + SLA date.",
    25,
    "standard",
  ),
  mission(
    "gcc_experiment_note",
    T.gcc,
    "Experiment log",
    "Record one experiment outcome (learned / inconclusive / scale) in GCC.",
    10,
    "intro",
  ),
  mission(
    "gcc_agent_brief_weekly",
    T.gcc,
    "Weekly agent brief",
    "File a brief: biggest win, biggest miss, one recovery action for next week.",
    25,
    "standard",
  ),
  mission(
    "gcc_suppression_audit",
    T.gcc,
    "Suppression audit",
    "Audit marketing suppression list—marketing emails only to consented, non-suppressed contacts.",
    50,
    "major",
  ),
  mission(
    "gcc_icp_refresh",
    T.gcc,
    "ICP refresh",
    "Re-read ICP definitions and mark one adjustment based on last week’s leads.",
    10,
    "intro",
  ),

  mission(
    "dist_lead_magnet_live",
    T.dist,
    "Lead magnet live",
    "AI-Age Starter Pack (or primary magnet) drives `/growth/lead` with suppression on.",
    50,
    "major",
    "marketing-site/src/pages/ai-age-starter-pack.astro",
  ),
  mission(
    "dist_attribution_utm",
    T.dist,
    "UTM hygiene",
    "Confirm landing links carry consistent UTM + campaign tags into analytics.",
    25,
    "standard",
  ),
  mission(
    "dist_seo_cluster_plan",
    T.dist,
    "SEO cluster plan",
    "Maintain a ranked list of 50 article topics + owner + target keyword.",
    25,
    "standard",
    "automation/n8n/workflows/seo_blog_engine.json",
  ),
  mission(
    "dist_n8n_imported",
    T.dist,
    "n8n workflows imported",
    "Core workflows imported on automation host; dry-run paths default ON.",
    25,
    "standard",
    "automation/n8n/README.md",
  ),
  mission(
    "dist_postiz_channels",
    T.dist,
    "Postiz channels wired",
    "At least one production channel connected; test post from Postiz succeeds.",
    50,
    "major",
    "automation/postiz/README.md",
  ),
  mission(
    "dist_social_calendar",
    T.dist,
    "2-week social calendar",
    "Publish calendar: topics, hooks, CTA, owner for the next 14 days.",
    25,
    "standard",
  ),
  mission(
    "dist_webinar_one",
    T.dist,
    "Webinar #1 scheduled",
    "Schedule one parent webinar with registration page + reminder emails.",
    50,
    "major",
  ),
  mission(
    "dist_creator_outreach_10",
    T.dist,
    "10 creator DMs",
    "Send 10 personalized creator/partner intros (logged in CRM or sheet).",
    25,
    "standard",
  ),
  mission(
    "dist_product_hunt_prep",
    T.dist,
    "Product Hunt prep",
    "Draft maker story, gallery assets, first-comment prep, and hunter coordination.",
    50,
    "major",
  ),
  mission(
    "dist_pr_narrative_doc",
    T.dist,
    "PR narrative one-pager",
    "Finalize angles: AI-age readiness, screen-light parenting, printable coaching.",
    25,
    "standard",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
  mission(
    "dist_reviews_reply_sla",
    T.dist,
    "Review reply SLA",
    "Set a 48h SLA for App/Play reviews; assign on-call for tone-safe replies.",
    25,
    "standard",
  ),

  mission(
    "rev_pricing_board_approved",
    T.part,
    "Pricing approved",
    "Formal sign-off on global $79 annual ladder + Pro band + India INR tiers.",
    50,
    "major",
    "src/lib/revenue/launchPricing.ts",
  ),
  mission(
    "rev_partner_pipeline_5",
    T.part,
    "5 partner convos",
    "Five real partner/clinic/employer conversations logged with next step + owner.",
    25,
    "standard",
  ),
  mission(
    "rev_pilot_contract_template",
    T.part,
    "Pilot contract template",
    "Pilot SoW or order form template ready (even draft under counsel review).",
    50,
    "major",
  ),
  mission(
    "rev_coverage_sdk_ping",
    T.part,
    "Coverage partner test",
    "Run a signed test hit to `POST /coverage/credit` in staging with cap behavior verified.",
    50,
    "major",
    "packages/coverage-partner-sdk/",
  ),
  mission(
    "rev_razorpay_live_ready",
    T.part,
    "Payments live-ready",
    "Razorpay (or chosen processor) webhooks + reconciliation path tested end-to-end.",
    50,
    "major",
  ),
  mission(
    "rev_invoice_ops",
    T.part,
    "Invoice ops",
    "Who issues invoices, numbering, tax line, and refund policy documented.",
    25,
    "standard",
  ),
  mission(
    "rev_affiliate_terms",
    T.part,
    "Affiliate / creator terms",
    "Lightweight terms for 100-creator affiliate push: payout, disclosure, brand.",
    50,
    "major",
  ),
  mission(
    "rev_employer_onepager",
    T.part,
    "Employer one-pager",
    "One-page ROI story for benefits leaders + pilot package.",
    25,
    "standard",
  ),

  mission(
    "trust_privacy_coppa_review",
    T.comp,
    "Privacy & kids data",
    "COPPA/GDPR checklist reviewed for current product scope; gaps ticketed.",
    50,
    "major",
    "docs/",
  ),
  mission(
    "trust_ai_disclaimers",
    T.comp,
    "AI disclaimers visible",
    "Coach/counselor surfaces carry non-diagnosis, supervision, and crisis boundaries.",
    25,
    "standard",
  ),
  mission(
    "trust_data_retention",
    T.comp,
    "Retention policy",
    "Document retention + delete flows for accounts and child-adjacent data.",
    50,
    "major",
  ),
  mission(
    "trust_incident_runbook",
    T.comp,
    "Incident runbook",
    "Security incident steps: containment, notify, log, postmortem template.",
    50,
    "major",
  ),
  mission(
    "trust_export_promise",
    T.comp,
    "Export promise tested",
    "Family backup/export exercised on production-like build yearly.",
    25,
    "standard",
  ),
  mission(
    "trust_consent_refresh",
    T.comp,
    "Consent copy refresh",
    "Marketing consent + product analytics consent language aligned with practices.",
    25,
    "standard",
  ),
  mission(
    "trust_access_review_quarterly",
    T.comp,
    "Admin access review",
    "Quarterly audit: `admin_users` roster matches humans; disable stale accounts.",
    25,
    "standard",
  ),
  mission(
    "trust_audit_log_sample",
    T.comp,
    "Audit log sample",
    "Pull a sample of `admin_audit_log` for mutations—verify actor + action hygiene.",
    10,
    "intro",
  ),

  mission(
    "scale_launch_definition",
    T.scale,
    "Global launch criteria",
    "App public + signups from 10 countries + $100k cumulative revenue—track in GCC.",
    100,
    "epic",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
  mission(
    "scale_channel_predictable",
    T.scale,
    "Predictable channel",
    "One channel hits predictable weekly revenue 4 weeks straight OR $1M cumulative.",
    100,
    "epic",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
  mission(
    "scale_1m_milestone",
    T.scale,
    "$1M cumulative",
    "Log the $1M checkpoint in GCC with evidence—not pipeline-only.",
    100,
    "epic",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
  mission(
    "scale_10m_milestone",
    T.scale,
    "$10M collected",
    "Signed or collected $10M; update playbook and investor narrative.",
    100,
    "epic",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
  mission(
    "scale_weekly_review_ritual",
    T.scale,
    "Weekly growth review",
    "Run the weekly review template with revenue + experiments + kill-switch section.",
    25,
    "standard",
    "docs/growth/WEEKLY_REVIEW_TEMPLATE.md",
  ),
  mission(
    "scale_geographic_expansion_plan",
    T.scale,
    "Geo expansion plan",
    "Pick next 2 priority markets after first wins; localize one lever (pricing, store, or social).",
    25,
    "standard",
    "docs/growth/GLOBAL_SCALE_PLAYBOOK.md",
  ),
];

const byKey = new Map(ADMIN_MISSIONS.map((m) => [m.key, m]));

export function getMissionByKey(key: string): MissionDef | undefined {
  return byKey.get(key);
}
